### ISSUE TITLE
BlueMapOfflineSkin error a player join (1.17)

### ISSUE THREAD

**Issue by fnltochka** [akemin-dayo/BlueMapOfflineSkinSupport#3]
Version: Purpur 1.17.1
Skin provider: SkinsRestorer 14.1.1
Bungee mode: true (Waterfall)
Skins are not displayed on the map

```
[15:51:30 ERROR]: [BlueMapOfflineSkinSupport] An error occurred while attempting to acquire the SkinsRestorer skin data for Steve's true skin!
[15:51:30 WARN]: net.skinsrestorer.shared.exception.ReflectionException: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "obj" is null
[15:51:30 WARN]:        at net.skinsrestorer.shared.utils.ReflectionUtil.invokeMethod(ReflectionUtil.java:254)
[15:51:30 WARN]:        at ai.akemi.bluemapofflineskinsupport.BlueMapOfflineSkinSupport.lambda$writeTrueCompositedPlayerHeadForBukkitPlayerAsynchronousCallback$0(BlueMapOfflineSkinSupport.java:124)
[15:51:30 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[15:51:30 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[15:51:30 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[15:51:30 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[15:51:30 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[15:51:30 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[15:51:30 WARN]: Caused by: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "obj" is null
[15:51:30 WARN]:        at net.skinsrestorer.shared.utils.ReflectionUtil.invokeMethod(ReflectionUtil.java:252)
[15:51:30 WARN]:        ... 7 more
```

**Comment by akemin-dayo** [comment]
This crash should be fixed with [version 1.3](https://github.com/akemin-dayo/BlueMapOfflineSkinSupport/releases/tag/1.3).

Please reopen this issue if you are still experiencing issues.
