### ISSUE TITLE
SkinsRestorerX throws an NPE while attempting to load a player skin

### ISSUE THREAD

**Issue by HerosteveFeed** [akemin-dayo/BlueMapOfflineSkinSupport#7]
```
[09:18:59 WARN]: [BlueMapOfflineSkinSupport] Plugin BlueMapOfflineSkinSupport v1.3 generated an exception while executing task 64
java.lang.NullPointerException: Cannot invoke "java.nio.file.Path.resolve(String)" because "this.playersFolder" is null
        at net.skinsrestorer.shared.storage.SkinStorage.getSkinOfPlayer(SkinStorage.java:175) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.api.SkinsRestorerAPI.getSkinName(SkinsRestorerAPI.java:85) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.api.SkinsRestorerAPI.hasSkin(SkinsRestorerAPI.java:95) ~[SkinsRestorer.jar:?]
        at ai.akemi.bluemapofflineskinsupport.BlueMapOfflineSkinSupport.lambda$writeTrueCompositedPlayerHeadForBukkitPlayerAsynchronousCallback$0(BlueMapOfflineSkinSupport.java:119) ~[BlueMapOfflineSkinSupport-1.3.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[pufferfish-1.19.jar:git-Pufferfish-6]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[pufferfish-1.19.jar:git-Pufferfish-6]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[pufferfish-1.19.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by akemin-dayo** [comment]
Apologies for the late reply.

That being said… looking at the stacktrace you posted, this seems to be an issue with _something_ in your SkinsRestorerX setup, instead of an incompatibility with 1.19.x (which I have verified is not the case — BMOSS is pretty version-agnostic anyway due to the way it's written).

Is this still happening for you on the latest versions of Paper and SkinsRestorerX?

If so, are you perhaps using the SQL skin storage backend? While BMOSS should _theoretically_ work fine with that since all I'm doing is asking SkinsRestorer to provide a skin to us, regardless of what the storage backend may be, I've never actually tested that particular configuration.

**Comment by akemin-dayo** [comment]
Closing for now. Feel free to reopen if you still experience issues with the latest versions of everything.
